// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StringServiceClient is the client API for StringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StringServiceClient interface {
	Concat(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringResponse, error)
	LotsOfServerStream(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (StringService_LotsOfServerStreamClient, error)
	LotsOfClientStream(ctx context.Context, opts ...grpc.CallOption) (StringService_LotsOfClientStreamClient, error)
	LotsOfServerAndClientStream(ctx context.Context, opts ...grpc.CallOption) (StringService_LotsOfServerAndClientStreamClient, error)
}

type stringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStringServiceClient(cc grpc.ClientConnInterface) StringServiceClient {
	return &stringServiceClient{cc}
}

func (c *stringServiceClient) Concat(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringResponse, error) {
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, "/pb.StringService/Concat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stringServiceClient) LotsOfServerStream(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (StringService_LotsOfServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StringService_ServiceDesc.Streams[0], "/pb.StringService/LotsOfServerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &stringServiceLotsOfServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StringService_LotsOfServerStreamClient interface {
	Recv() (*StringResponse, error)
	grpc.ClientStream
}

type stringServiceLotsOfServerStreamClient struct {
	grpc.ClientStream
}

func (x *stringServiceLotsOfServerStreamClient) Recv() (*StringResponse, error) {
	m := new(StringResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stringServiceClient) LotsOfClientStream(ctx context.Context, opts ...grpc.CallOption) (StringService_LotsOfClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StringService_ServiceDesc.Streams[1], "/pb.StringService/LotsOfClientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &stringServiceLotsOfClientStreamClient{stream}
	return x, nil
}

type StringService_LotsOfClientStreamClient interface {
	Send(*StringRequest) error
	CloseAndRecv() (*StringResponse, error)
	grpc.ClientStream
}

type stringServiceLotsOfClientStreamClient struct {
	grpc.ClientStream
}

func (x *stringServiceLotsOfClientStreamClient) Send(m *StringRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *stringServiceLotsOfClientStreamClient) CloseAndRecv() (*StringResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StringResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stringServiceClient) LotsOfServerAndClientStream(ctx context.Context, opts ...grpc.CallOption) (StringService_LotsOfServerAndClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StringService_ServiceDesc.Streams[2], "/pb.StringService/LotsOfServerAndClientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &stringServiceLotsOfServerAndClientStreamClient{stream}
	return x, nil
}

type StringService_LotsOfServerAndClientStreamClient interface {
	Send(*StringRequest) error
	Recv() (*StringResponse, error)
	grpc.ClientStream
}

type stringServiceLotsOfServerAndClientStreamClient struct {
	grpc.ClientStream
}

func (x *stringServiceLotsOfServerAndClientStreamClient) Send(m *StringRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *stringServiceLotsOfServerAndClientStreamClient) Recv() (*StringResponse, error) {
	m := new(StringResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StringServiceServer is the server API for StringService service.
// All implementations must embed UnimplementedStringServiceServer
// for forward compatibility
type StringServiceServer interface {
	Concat(context.Context, *StringRequest) (*StringResponse, error)
	LotsOfServerStream(*StringRequest, StringService_LotsOfServerStreamServer) error
	LotsOfClientStream(StringService_LotsOfClientStreamServer) error
	LotsOfServerAndClientStream(StringService_LotsOfServerAndClientStreamServer) error
	mustEmbedUnimplementedStringServiceServer()
}

// UnimplementedStringServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStringServiceServer struct {
}

func (UnimplementedStringServiceServer) Concat(context.Context, *StringRequest) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Concat not implemented")
}
func (UnimplementedStringServiceServer) LotsOfServerStream(*StringRequest, StringService_LotsOfServerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method LotsOfServerStream not implemented")
}
func (UnimplementedStringServiceServer) LotsOfClientStream(StringService_LotsOfClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method LotsOfClientStream not implemented")
}
func (UnimplementedStringServiceServer) LotsOfServerAndClientStream(StringService_LotsOfServerAndClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method LotsOfServerAndClientStream not implemented")
}
func (UnimplementedStringServiceServer) mustEmbedUnimplementedStringServiceServer() {}

// UnsafeStringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StringServiceServer will
// result in compilation errors.
type UnsafeStringServiceServer interface {
	mustEmbedUnimplementedStringServiceServer()
}

func RegisterStringServiceServer(s grpc.ServiceRegistrar, srv StringServiceServer) {
	s.RegisterService(&StringService_ServiceDesc, srv)
}

func _StringService_Concat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StringServiceServer).Concat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.StringService/Concat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StringServiceServer).Concat(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StringService_LotsOfServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StringRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StringServiceServer).LotsOfServerStream(m, &stringServiceLotsOfServerStreamServer{stream})
}

type StringService_LotsOfServerStreamServer interface {
	Send(*StringResponse) error
	grpc.ServerStream
}

type stringServiceLotsOfServerStreamServer struct {
	grpc.ServerStream
}

func (x *stringServiceLotsOfServerStreamServer) Send(m *StringResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StringService_LotsOfClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StringServiceServer).LotsOfClientStream(&stringServiceLotsOfClientStreamServer{stream})
}

type StringService_LotsOfClientStreamServer interface {
	SendAndClose(*StringResponse) error
	Recv() (*StringRequest, error)
	grpc.ServerStream
}

type stringServiceLotsOfClientStreamServer struct {
	grpc.ServerStream
}

func (x *stringServiceLotsOfClientStreamServer) SendAndClose(m *StringResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *stringServiceLotsOfClientStreamServer) Recv() (*StringRequest, error) {
	m := new(StringRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StringService_LotsOfServerAndClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StringServiceServer).LotsOfServerAndClientStream(&stringServiceLotsOfServerAndClientStreamServer{stream})
}

type StringService_LotsOfServerAndClientStreamServer interface {
	Send(*StringResponse) error
	Recv() (*StringRequest, error)
	grpc.ServerStream
}

type stringServiceLotsOfServerAndClientStreamServer struct {
	grpc.ServerStream
}

func (x *stringServiceLotsOfServerAndClientStreamServer) Send(m *StringResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *stringServiceLotsOfServerAndClientStreamServer) Recv() (*StringRequest, error) {
	m := new(StringRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StringService_ServiceDesc is the grpc.ServiceDesc for StringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.StringService",
	HandlerType: (*StringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Concat",
			Handler:    _StringService_Concat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LotsOfServerStream",
			Handler:       _StringService_LotsOfServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LotsOfClientStream",
			Handler:       _StringService_LotsOfClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "LotsOfServerAndClientStream",
			Handler:       _StringService_LotsOfServerAndClientStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/string.proto",
}
